package sss

import (
	"bytes"
	"encoding/binary"
	"io"

	"go.dedis.ch/kyber/v3"
	"go.dedis.ch/kyber/v3/share"
)

// SecretShare holds the share of a key.
type SecretShare struct {
	share   *share.PriShare
	commits []kyber.Point
}

// PriShare returns the private share.
func (s *SecretShare) PriShare() *share.PriShare {
	return s.share
}

// Commitments returns the coefficients of the public polynomial.
func (s *SecretShare) Commitments() []kyber.Point {
	return s.commits
}

// Public returns the public key associated with the distributed private key.
func (s *SecretShare) Public() kyber.Point {
	return s.commits[0]
}

// Threshold returns the secret sharing threshold.
func (s *SecretShare) Threshold() int {
	return len(s.commits)
}

// MarshalBinary encodes the receiver into a binary form and returns the result.
func (s *SecretShare) MarshalBinary() ([]byte, error) {
	b := &bytes.Buffer{}

	_, err := varintMarshalTo(int64(s.share.I), b)
	if err != nil {
		return b.Bytes(), err
	}
	_, err = s.share.V.MarshalTo(b)
	if err != nil {
		return b.Bytes(), err
	}
	for _, commit := range s.commits {
		_, err = commit.MarshalTo(b)
		if err != nil {
			return b.Bytes(), err
		}
	}
	return b.Bytes(), nil
}

func (s *SecretShare) String() string {
	b, err := s.MarshalBinary()
	if err != nil {
		panic(err)
	}
	return string(b)
}

// UnmarshalSecretShare decodes the data generated by SecretShare.MarshalBinary with respect to the given group.
func UnmarshalSecretShare(group kyber.Group, data []byte) (*SecretShare, error) {
	b := bytes.NewBuffer(data)
	s := &SecretShare{}

	i, err := binary.ReadVarint(b)
	if err != nil {
		return nil, err
	}
	v := group.Scalar()
	_, err = v.UnmarshalFrom(b)
	if err != nil {
		return nil, err
	}
	s.share = &share.PriShare{I: int(i), V: v}

	s.commits = []kyber.Point{}
	for b.Len() > 0 {
		p := group.Point()
		_, err = p.UnmarshalFrom(b)
		if err != nil {
			return nil, err
		}
		s.commits = append(s.commits, p)
	}
	return s, nil
}

func varintMarshalTo(x int64, w io.Writer) (int, error) {
	var tmp [binary.MaxVarintLen64]byte
	n := binary.PutVarint(tmp[:], x)
	return w.Write(tmp[:n])
}
